artifact_location: /Users/ranvirsinghvirk/Eclipse/DS Practice/Olist_MTL_Pipeline/127.0.0.1:5000/0
creation_time: 1773917021556
experiment_id: '0'
last_update_time: 1773917021556
lifecycle_stage: active
name: Default
workspace: default
